from setuptools import setup, find_packages

setup(
    name="goblintools",
    version="0.9.0",
    packages=find_packages(),
    install_requires=[
        "patool",
        "rarfile",
        "boto3",
        "opencv-python-headless",
        "numpy",
        "pdf2image",
        "pypdf>=6.10.2",
        "pdfplumber",
        "cryptography>=3.1",
        "beautifulsoup4",
        "striprtf",
        "dbfread",
        "python-docx",
        "python-pptx",
        "openpyxl",
        "xlrd",
        "odfpy",
        "unidecode",
        "pytesseract",
        "scipy",
        "pillow"
    ],
    author="Gean Matos",
    author_email="gean@webgoal.com.br",
    description="Toolkit for archive extraction, OCR parsing, and file text extraction",
    license="MIT",
    include_package_data=True,
)
